shop/apps/orders/urls.py
from django.urls import path
from .views import *

app_name='orders'
urlpatterns = [
    path('shop_cart/',ShopCartVeiw.as_view(),name='shop_cart'),
    path('show_shop_cart/',show_shop_cart,name='show_shop_cart'),
    path('add_to_shop_cart/',add_to_shop_cart,name='add_to_shop_cart'),
    path('delete_from_shop_cart/',delete_from_shop_cart,name='delete_from_shop_cart'),
    path('update_shop_cart/',update_shop_cart,name='update_shop_cart'),
    path('status_shop_cart/',status_shop_cart,name='status_shop_cart'),
    path('create_order/<int:order_final_price>/',CreateOrderView.as_view(),name='create_order'),
    path('checkout_order/<int:order_id>/',CheckoutOrderView.as_view(),name='checkout_order'),
    # path('applay_coupon/<int:order_id>/',ApplayCoupon.as_view(),name='applay_coupon'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls',namespace='main')),
    path('products/', include('apps.products.urls',namespace='products')),
    path('accounts/', include('apps.accounts.urls',namespace='accounts')),
    path('cs/', include('apps.comment_scoring.urls',namespace='cs')),
    path('orders/', include('apps.orders.urls',namespace='orders')),
    
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/apps/orders/models.py
from django.db import models
from apps.accounts.models import Customer,CustomUser
import uuid
import utils
from apps.products.models import Product
from django.utils import timezone
#=========================================================================
class OrderState(models.Model):
    title=models.CharField(max_length=100,verbose_name='وضعیت سفارش')
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name='وضعیت سفارش'
        verbose_name_plural='انواع وضعیت سفارش'
#=========================================================================
class PaymentType(models.Model):
    title=models.CharField(max_length=100,verbose_name='نوع پرداخت')
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name='نوع پرداخت'
        verbose_name_plural='انواع روش پرداخت'
#=========================================================================
class Order(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE,verbose_name='مشتری',related_name='customer')
    register_date=models.DateTimeField(auto_now_add=True,verbose_name='تاریخ ثبت سفارش')
    update_date=models.DateTimeField(auto_now=True,verbose_name='تاریخ آپدیت سفارش')
    order_code=models.UUIDField(unique=True,default=uuid.uuid4,editable=False,verbose_name='کد تولیدی برای سفارش')
    order_state=models.ForeignKey(OrderState,default=None,null=True,blank=True,on_delete=models.CASCADE,verbose_name='وضعیت سفارش',related_name='order_states')
    description=models.TextField(verbose_name='توضیحات سفارش')
    payment_type=models.ForeignKey(PaymentType,default=None,on_delete=models.CASCADE,null=True,blank=True,related_name='payment_type',verbose_name='نوع پرداخت')
    is_finaly=models.BooleanField(default=False,verbose_name='نهایی شده')
    
    def __str__(self):
        return f'{self.customer}\t{self.id}\t{self.is_finaly}'
    
    def get_order_total_price(self):
        sum=0
        for item in self.order_details1.all():
            sum+=item.product.price*item.qty
        order_final_price,delivery,tax=utils.price_by_delivery_tax(sum)
        return int(order_final_price*10)
    
    class Meta:
        verbose_name='سفارش'
        verbose_name_plural='سفارشات'
#=========================================================================
class OrderDetails(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE,verbose_name='سفارش',related_name='order_details1')
    product=models.ForeignKey(Product,on_delete=models.CASCADE,verbose_name='کالا',related_name='order_details2')
    qty=models.PositiveSmallIntegerField(default=1,verbose_name='تعداد')
    price=models.IntegerField(verbose_name='قیمت کالا در فاکتور')
    
    def __str__(self):
        return f'{self.order}\t{self.product}\t{self.qty}\t{self.price}'
#=========================================================================
class Payment(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE,verbose_name='سفارش',related_name='payment_order')
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE,verbose_name='مشتری',related_name='payment_customer')
    register_date=models.DateTimeField(default=timezone.now,verbose_name='تاریخ پرداخت')
    update_date=models.DateTimeField(auto_now=True,verbose_name='تاریخ ویرایش پرداخت')
    amount=models.IntegerField(verbose_name='مبلغ پرداخت')
    is_finally=models.BooleanField(default=False,verbose_name='وضعیت پرداخت')
    status_code=models.IntegerField(verbose_name='کد وضعیت درگاه پرداخت',null=True,blank=True)
    ref_id=models.CharField(max_length=50,verbose_name='شماره پیگیری پرداخت',null=True,blank=True)
    
    def __str__(self):
        return f'{self.order} {self.customer} {self.ref_id}'
    
    class Meta:
        verbose_name='پرداخت'
        verbose_name_plural='پرداخت ها'
#=========================================================================
class WarehouseType(models.Model):
    warehouse_type_title=models.CharField(max_length=50,verbose_name='نوع انبار')
    
    def __str__(self):
        return self.warehouse_type_title
    
    class Meta:
        verbose_name='نوع انبار'
        verbose_name_plural='انواع روش انبار'
#=========================================================================
class Warehouse(models.Model):
    warehouse_type=models.ForeignKey(WarehouseType,on_delete=models.CASCADE,related_name='Warehouses',verbose_name='انبار')
    user_registered=models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='warehouseuser_registered',verbose_name='کاربر')
    product=models.ForeignKey(Product,on_delete=models.CASCADE,related_name='warehouse_products',verbose_name='کالا')
    qty=models.IntegerField(verbose_name='تعداد')
    price=models.IntegerField(verbose_name='قیمت واحد',null=True,blank=True)
    register_date=models.DateTimeField(auto_now_add=True,verbose_name='تاریخ ثبت')
    
    def __str__(self):
        return f'{self.warehouse_type} - {self.product}'
    
    class Meta:
        verbose_name='انبار'
        verbose_name_plural='انبار ها'
#=========================================================================
        

shop/apps/orders/forms.py
from django import forms
from .models import PaymentType

class OrderForm(forms.Form):
    name=forms.CharField(label='',
                         widget=forms.TextInput(attrs={'class':'form-control','placeholder':'نام'}),
                         error_messages={'required':'این فیلد نمی تواند خالی باشد'})
    
    family=forms.CharField(label='',
                         widget=forms.TextInput(attrs={'class':'form-control','placeholder':'نام خانوادگی'}),
                         error_messages={'required':'این فیلد نمی تواند خالی باشد'})
    
    email=forms.CharField(label='',
                         widget=forms.TextInput(attrs={'class':'form-control','placeholder':'ایمیل'}),
                         required=False)    
    
    phone_number=forms.CharField(label='',
                         widget=forms.TextInput(attrs={'class':'form-control','placeholder':'تلفن'}),
                         required=False)  
      
    address=forms.CharField(label='',
                         widget=forms.Textarea(attrs={'class':'form-control','placeholder':'آدرس','rows':"3"}),
                         error_messages={'required':'این فیلد نمی تواند خالی باشد'})
    
    description=forms.CharField(label='',
                         widget=forms.Textarea(attrs={'class':'form-control','placeholder':'توضیحات','rows':"5"}),
                         required=False)    

    payment_type=forms.ChoiceField(label='',
                                   choices=[(item.id,item) for item in PaymentType.objects.all()],
                                   widget=forms.RadioSelect())

shop/apps/orders/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views import View
from .shop_cart import ShopCart
from apps.products.models import Product
from apps.accounts.models import Customer
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Order,OrderDetails,PaymentType,OrderState
from .forms import OrderForm
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from datetime import datetime
from django.contrib import messages
import utils
from .models import Payment,Warehouse,WarehouseType
#--------------------------------------------------------------
class ShopCartVeiw(View):
    def get(self,request, *args, **kwargs):
        shop_cart=ShopCart(request)
        context={
            'shop_cart':shop_cart,
        }
        return render(request,'orders/shop_cart.html',context)
#--------------------------------------------------------------
def show_shop_cart(request):
        shop_cart=ShopCart(request)
        total_price=shop_cart.calc_total_price()
        order_final_price,delivery,tax=utils.price_by_delivery_tax(total_price)
        
        context={
            'shop_cart':shop_cart,
            'shop_cart_count':shop_cart.count,
            "total_price":total_price,
            "delivery":delivery,
            "tax":int(tax),
            "order_final_price":int(order_final_price), 
        }
        return render(request,'orders/partials/show_shop_cart.html',context)
#--------------------------------------------------------------
def add_to_shop_cart(request):
    product_id=request.GET.get('product_id')
    qty=request.GET.get('qty')
    shop_cart=ShopCart(request)
    product=get_object_or_404(Product,id=product_id)
    shop_cart.add_to_shop_cart(product,qty)
    return HttpResponse(shop_cart.count)
#--------------------------------------------------------------
def delete_from_shop_cart(request):
    product_id=request.GET.get('product_id')
    product=get_object_or_404(Product,id=product_id)
    shop_cart=ShopCart(request)
    shop_cart.delete_from_shop_cart(product)
    return redirect('orders:show_shop_cart')
#--------------------------------------------------------------
def update_shop_cart(request):
    product_id_list=request.GET.getlist('product_id_list[]')
    qty_list=request.GET.getlist('qty_list[]')
    shop_cart=ShopCart(request)
    shop_cart.update(product_id_list,qty_list)    
    return redirect('orders:show_shop_cart')
#--------------------------------------------------------------
def status_shop_cart(request):
    shop_cart=ShopCart(request)
    return HttpResponse(shop_cart.count)
#--------------------------------------------------------------
class CreateOrderView(LoginRequiredMixin,View):
    def get(self,request,order_final_price):
        try:
            customer=Customer.objects.get(user=request.user)
        except ObjectDoesNotExist:
            customer=Customer.objects.create(user=request.user)
        
        order=Order.objects.create(customer=customer,payment_type=get_object_or_404(PaymentType,id=1))
        order.order_state=OrderState.objects.get(id=5)
        order.save()
        Payment.objects.create(
                order=order,
                customer=Customer.objects.get(user=request.user),
                amount=order_final_price,
                )
        
        shop_cart=ShopCart(request)
        for item in shop_cart:
            product=Product.objects.get(id=item['product'].id)
            if product.get_number_in_warehouse() >= item['qty']:
                OrderDetails.objects.create(
                order=order,
                product=item['product'],
                price=item['price'],
                qty=item['qty']
                )
            else:
                message1=f'درحال حاضر فقط تعداد {product.get_number_in_warehouse()} کالا {item['product']} در انبار موجود میباشد'
                message2=f'درحال حاضر کالای {item['product']} در انبار موجود نمیباشد'
                if product.get_number_in_warehouse() == 0:
                    messages.error(request,message2,'danger')
                else:
                    messages.error(request,message1,'danger')
                    
                return redirect('orders:shop_cart')
        return redirect('orders:checkout_order',order.id)
#--------------------------------------------------------------
class CheckoutOrderView(LoginRequiredMixin,View):
    def get(self,request,order_id):
        user=request.user
        customer=get_object_or_404(Customer,user=user)
        shop_cart=ShopCart(request)
        order=get_object_or_404(Order,id=order_id)
        
        total_price=shop_cart.calc_total_price()
        order_final_price,delivery,tax=utils.price_by_delivery_tax(total_price)

        
        data={
            'name':user.name,
            'family':user.family,
            'email':user.email,
            "phone_number":customer.mobile_number,
            "address":customer.address,
            'description':order.description,
            'payment_type':order.payment_type
            
        }
        form=OrderForm(data)
        context={
            'shop_cart':shop_cart,
            'form':form,
            "total_price":total_price,
            "delivery":delivery,
            "tax":int(tax),
            "order_final_price":int(order_final_price), 
            "order":order, 
        }
        
        return render(request,'orders/checkout.html',context)
    
    def post(self,request,order_id):
        form=OrderForm(request.POST)
        order_final_price = request.POST.get('order_final_price')
        order_final_price=int(order_final_price)
        
        if form.is_valid():
            cd=form.cleaned_data
            try:
                order=Order.objects.get(id=order_id)
                order.description=cd['description']
                order.payment_type = PaymentType.objects.get(id=cd['payment_type'])
                order.save()
                
                user=request.user
                user.name=cd['name']
                user.family=cd['family']
                user.email=cd['email']
                user.save()
                
                customer=Customer.objects.get(user=user)
                customer.phone_number=cd['phone_number']
                customer.address=cd['address']
                customer.save()
                
                #چون درگاه پرداخت نداریم جزییات فروش را همینجا ثبت میکنیم
                for item in order.order_details1.all():
                    Warehouse.objects.create(
                        warehouse_type=WarehouseType.objects.get(id=2),
                        user_registered=request.user,
                        product=item.product,
                        qty=item.qty,
                        price=item.price
                    )
                    
                description="پرداخت از طریق درگاه زرین پال"
                payment=Payment.objects.get(order=order)
                if payment:
                    payment.is_finally=True
                    payment.amount=order_final_price
                    payment.save()
                else:
                    payment=Payment.objects.create(
                    order=order,
                    customer=Customer.objects.get(user=request.user),
                    amount=order_final_price,
                    )
                
                    payment.is_finally=True
                    payment.save()
                
                order.is_finaly=True
                order.order_state=OrderState.objects.get(id=1)
                order.save()
                 
                messages.success(request,'سفارش با موفقیت ثبت شد')
                return redirect('main:index')
                
            except ObjectDoesNotExist:
                messages.error(request,'فاکتوری با این مشخصات یافت نشد','danger')
                return redirect('orders:checkout_order', order_id)
        return redirect('orders:checkout_order', order_id)
#---------------------------------------------------------------------

shop/templates/orders/partials/show_shop_cart.html
{% load humanize %}
{% if shop_cart_count %}
<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html">خانه</a>
									/
								</li>
								<li class="breadcrumb-item active" aria-current="page">سبد خرید</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title">
						<h1>سبد خرید</h1></div>
				</div>
			</div>
			<div class="cart block">
				<div class="container">
					<table class="cart__table cart-table">
						<thead class="cart-table__head">
							<tr class="cart-table__row">
								<th class="cart-table__column cart-table__column--image">تصویر</th>
								<th class="cart-table__column cart-table__column--product">محصول</th>
								<th class="cart-table__column cart-table__column--price">قیمت</th>
								<th class="cart-table__column cart-table__column--quantity">تعداد</th>
								<th class="cart-table__column cart-table__column--total">جمع کل</th>
								<th class="cart-table__column cart-table__column--remove"></th>
							</tr>
						</thead>
						<tbody class="cart-table__body">
                            {% for item in shop_cart %}
                                <tr class="cart-table__row">
                                    <td class="cart-table__column cart-table__column--image">
                                        <a href=""><img src="{{media}}/{{item.product.image_name}}" alt=""></a>
                                    </td>
                                    <td class="cart-table__column cart-table__column--product">
                                        <a href="" class="cart-table__product-name">
                                            {{item.product.product_name}}
                                        </a>
                                    </td>
                                    <td class="cart-table__column cart-table__column--price" data-title="قیمت">
										{% if item.price > item.final_price %}
											<span style="font-size: 15px; color: red;">
												<del>
													{{item.price|intcomma}} تومان
												</del>
											</span>
											{{item.final_price|intcomma}} تومان
										{% else %}
											{{item.price|intcomma}} تومان
										{% endif %}
									</td>
                                    <td class="cart-table__column cart-table__column--quantity" data-title="تعداد">
                                        <div class="input-number">
                                            <input id="qty_{{item.product.id}}" type="number" min="1" value="{{item.qty}}" style="width: 60px;">
                                            {% comment %} <div class="input-number__add"></div>
                                            <div class="input-number__sub"></div> {% endcomment %}
                                        </div>
                                    </td>
                                    <td class="cart-table__column cart-table__column--total" data-title="جمع کل">{{item.total_price|intcomma}} تومان</td>
                                    <td class="cart-table__column cart-table__column--remove">
                                        <button type="button" class="btn btn-light btn-sm btn-svg-icon" onclick="delete_from_shop_cart({{item.product.id}})">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
						</tbody>
					</table>
					<div class="cart__actions">
						{% comment %} <form class="cart__coupon-form">
							<label for="input-coupon-code" class="sr-only">رمز عبور</label>
							<input type="text" class="form-control" id="input-coupon-code" placeholder="کد تخفیف">
							<button type="submit" class="btn btn-primary">اعمال کد تخفیف</button>
						</form> {% endcomment %}
						<div class="cart__buttons">
                            {% comment %} <a href="index.html" class="btn btn-light">ادامه خرید</a> {% endcomment %}
                            <a onclick="update_shop_cart()" class="btn btn-primary cart__update-button"> به روزرسانی سبد</a></div>
					</div>
					<div class="row justify-content-end pt-5">
						<div class="col-12 col-md-7 col-lg-6 col-xl-5">
							<div class="card">
								<div class="card-body">
									<h3 class="card-title">مجموع سبد</h3>
									<table class="cart__totals">
										<thead class="cart__totals-header">
											<tr>
												<th>جمع جزء</th>
												<td>{{total_price|intcomma}} تومان</td>
											</tr>
										</thead>
										<tbody class="cart__totals-body">
											<tr>
												<th>حمل و نقل</th>
                                                {% if delivery == 0 %}
                                                <td>رایگان
													{% comment %} <div class="cart__calc-shipping"><a href="#">محاسبه هزینه</a></div> {% endcomment %}
												</td>
                                                {% else %}
												<td>{{delivery|intcomma}} تومان
													{% comment %} <div class="cart__calc-shipping"><a href="#">محاسبه هزینه</a></div> {% endcomment %}
												</td>
                                                {% endif %}
											</tr>
											<tr>
												<th>مالیات</th>
												<td>{{tax|intcomma}} تومان</td>
											</tr>
										</tbody>
										<tfoot class="cart__totals-footer">
											<tr>
												<th>جمع کل</th>
												<td>{{order_final_price|intcomma}} تومان</td>
											</tr>
										</tfoot>
									</table><a class="btn btn-primary btn-xl btn-block cart__checkout-button" href="{% url "orders:create_order" order_final_price=order_final_price %}">ادامه خرید</a></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
{% else %}
{% include "partials/products/not_found_product.html" with title='🛒 اوه! اینجا خیلی خلوته 😅 یه چیزی به سبدت اضافه کن!' %}
{% endif %}